version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dentist_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dentist_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dentist_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db:3306/dentist_db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000/api # Para acesso via navegador no host
        # Se a comunicação fosse interna entre containers e o frontend servisse APIs:
        # VITE_API_URL: http://backend:5000/api
    container_name: dentist_frontend
    ports:
      - "3001:3001" # Mapeia a porta 3001 do host para a 3001 do container
    depends_on:
      - backend
    # Adicionar environment aqui se o CMD no Dockerfile não pegar o ARG/ENV corretamente para o preview
    # environment:
    #   VITE_API_URL: http://localhost:5000/api

volumes:
  mysql_data:


